# Updated joint_controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    hand_group_controller:
       type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - joint1_21p0017_21p0088
      - joint2_21p0017_21p0088
      - joint3_21p0017_21p0088
      - joint4_21p0017_21p0088
      - joint5_21p0017_21p0088
      - joint6_21p0017_21p0088
     
    command_interfaces: [position]
    state_interfaces: [position, velocity]

    allow_nonzero_velocity_at_trajectory_end: true
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5
      joint1_21p0017_21p0088:
        trajectory: 0.05
        goal: 0.03
      joint2_21p0017_21p0088:
        trajectory: 0.05
        goal: 0.03
      joint3_21p0017_21p0088:
        trajectory: 0.05
        goal: 0.03
      joint4_21p0017_21p0088:
        trajectory: 0.05
        goal: 0.03
      joint5_21p0017_21p0088:
        trajectory: 0.05
        goal: 0.03
      joint6_21p0017_21p0088:
        trajectory: 0.05
        goal: 0.03
        
hand_group_controller:
  ros__parameters:
    joints:
      - joint7_21p0017_21p0088
      - joint8_21p0017_21p0088
      

    command_interfaces: [position]
    state_interfaces: [position, velocity]

    allow_nonzero_velocity_at_trajectory_end: true
    gains: # optional , but for better control (PID)
        joint7_21p0017_21p0088: {p: 500.0, i: 10.0, d: 10.0}
        joint8_21p0017_21p0088: {p: 500.0, i: 10.0, d: 10.0}
        