# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - joint1_21p0017_21p0088
      - joint2_21p0017_21p0088
      - joint3_21p0017_21p0088
      - joint4_21p0017_21p0088
      - joint5_21p0017_21p0088
      - joint6_21p0017_21p0088
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
hand_group_controller:
  ros__parameters:
    joints:
      - joint7_21p0017_21p0088
      - joint8_21p0017_21p0088
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true